### ISSUE TITLE
Module not found: Error: Can't resolve 'webpack-hot-client/client?main'

### ISSUE THREAD

**Issue by lutangar** [webpack-contrib/webpack-hot-client#8]
* Operating System: Linux
* Node Version: v8.9.3
* NPM Version: 5.5.1
* webpack Version: ^3.10.0
* webpack-dev-server Version: N/A

- [x] This is a **bug**
- [ ] This is a **feature** request
- [ ] This is a **modification** request

### Code

I'll try to provide a simpler example, meanwhile, here is the full code:

*Entry point where the dev middleware is loaded*
https://github.com/larriereguichet/universal-react-app/blob/webpack-hot-client/src/server/index.js

*Webpack client configuration used by the middleware*
https://github.com/larriereguichet/universal-react-app/blob/webpack-hot-client/packages/webpack-config/src/client.js

*`webpack-hot-client` configuration*
https://github.com/larriereguichet/universal-react-app/blob/webpack-hot-client/packages/react-dev-middleware/src/index.js

### Expected Behavior
N/A

### Actual Behavior
```
ERROR in multi webpack-hot-client/client?main ./src/client/index.js
Module not found: Error: Can't resolve 'webpack-hot-client/client?main' in '...'
```

### For Bugs; How can we reproduce the behavior?
```
git clone git@github.com:larriereguichet/universal-react-app.git
cd universal-react-app
git checkout webpack-hot-client
lerna bootstrap
lerna run build
npm start
```
### For Features; What is the motivation and/or use-case for the feature?
N/A

**Comment by lutangar** [comment]
> @lutangar Are you using more than one webpack compiler instance at the same time? I met the same error when I implemented SSR before, but I've fixed it through this commit 87de9e6 .

@JounQin I don't think my server side webpack compiler is involved here, as both configurations are isolated.
Also the `target` is set to `web` on the client configuration.

**Comment by shellscape** [comment]
https://github.com/larriereguichet/universal-react-app/blob/webpack-hot-client/packages/webpack-config/src/client.js#L60

To start, you don't need to declare this here. hot-client takes care of that. 

Still looking at the rest...

**Comment by shellscape** [comment]
Could the issue be that you have webpack-hot-**middleware** in deps instead of webpack-hot-client? https://github.com/larriereguichet/universal-react-app/blob/webpack-hot-client/packages/react-dev-middleware/package.json#L30

**Comment by lutangar** [comment]
> Could the issue be that you have webpack-hot-middleware in deps instead of webpack-hot-client? https://github.com/larriereguichet/universal-react-app/blob/webpack-hot-client/packages/react-dev-middleware/package.json#L30

Sorry, I did this as I was preparing the branch, the correct version has been pushed. And ofc problem occurred with the correct dependency.

**Comment by shellscape** [comment]
What's `npm ls` look like for this module?

**Comment by lutangar** [comment]
`npm ls --depth=1`


react-dev-middleware@2.1.3
├─┬ `@babel/cli@7.0.0-beta.37`
│ ├── chokidar@1.7.0
│ ├── commander@2.13.0
│ ├── convert-source-map@1.5.1
│ ├── fs-readdir-recursive@1.1.0
│ ├── glob@7.1.2
│ ├── lodash@4.17.4
│ ├── output-file-sync@2.0.0
│ ├── slash@1.0.0
│ └── source-map@0.5.7
├── UNMET PEER DEPENDENCY `@babel/core@7.0.0-beta.37`
├─┬ cross-env@5.1.3
│ ├── cross-spawn@5.1.0
│ └── is-windows@1.0.1
├─┬ expect@22.1.0
│ ├── ansi-styles@3.2.0
│ ├── jest-diff@22.1.0
│ ├── jest-get-type@22.1.0
│ ├── jest-matcher-utils@22.1.0
│ ├── jest-message-util@22.1.0
│ └── jest-regex-util@22.1.0
├── lodash.isfunction@3.0.8
├─┬ rimraf@2.6.2
│ └── glob@7.1.2 deduped
├─┬ webpack@3.10.0
│ ├── acorn@5.3.0
│ ├── acorn-dynamic-import@2.0.2
│ ├── ajv@5.5.2
│ ├── ajv-keywords@2.1.1
│ ├── async@2.6.0
│ ├── enhanced-resolve@3.4.1
│ ├── escope@3.6.0
│ ├── interpret@1.1.0
│ ├── json-loader@0.5.7
│ ├── json5@0.5.1
│ ├── loader-runner@2.3.0
│ ├── loader-utils@1.1.0
│ ├── memory-fs@0.4.1
│ ├── mkdirp@0.5.1
│ ├── node-libs-browser@2.1.0
│ ├── source-map@0.5.7 deduped
│ ├── supports-color@4.5.0
│ ├── tapable@0.2.8
│ ├── uglifyjs-webpack-plugin@0.4.6
│ ├── watchpack@1.4.0
│ ├── webpack-sources@1.1.0
│ └── yargs@8.0.2
├─┬ webpack-dev-middleware@2.0.4
│ ├── loud-rejection@1.6.0
│ ├── memory-fs@0.4.1 deduped
│ ├── mime@2.2.0
│ ├── path-is-absolute@1.0.1
│ ├── range-parser@1.2.0
│ ├── url-join@2.0.5
│ └── webpack-log@1.1.1
└─┬ webpack-hot-client@1.0.8 (git://github.com/webpack-contrib/webpack-hot-client.git#ad117c67be13df6884354e11355dc5c0fc69a15b)
  ├── loglevelnext@1.0.3
  ├── uuid@3.1.0
  ├── webpack-log@1.1.1 deduped
  └── ws@3.3.3

**Comment by shellscape** [comment]
And to make sure we're covering all bases here; what's the file structure of the webpack-hot-client directory in node_modules?

**Comment by shellscape** [comment]
OK so the issue was that NPM is having fits running prepublish/prepare scripts when installing from a git repo with a branch on the end, so none of the client files were being generated. Sheesh. I pushed the client files to the branch for the purposes of testing, so reinstall and you should be good. (These will be removed before the branch is merged, and file preparation should be normal on install from npm)

**Comment by lutangar** [comment]
>what's the file structure of the webpack-hot-client directory in node_modules?

Ho, I see where you are heading: 
```
├── client
├── HotClientEntryPlugin.js
├── index.js
├── lib
│   └── util.js
├── LICENSE
├── package.json
└── README.md
```
The content of lib/client was missing in the last version...

> I pushed the client files to the branch for the purposes of testing, so reinstall and you should be good. (These will be removed before the branch is merged, and file preparation should be normal on install from npm)

Alright:
```
.
├── client
│   ├── hot.js
│   ├── index.js
│   ├── log.js
│   └── socket.js
├── HotClientEntryPlugin.js
├── index.js
├── lib
│   └── util.js
├── LICENSE
├── package.json
└── README.md
```
Still the issue persists, I'm pretty convinced I had the same error prior to this version.
I'll come back with a simpler example to demonstrate the issue so you won't waste anymore time.
Thanks anyway.

**Comment by shellscape** [comment]
The module structure looks good now at least. I can't figure out a reason why `webpack-hot-client/client` wouldn't be picked up.

**Comment by shellscape** [comment]
@lutangar has this been resolved by recent versions?

**Comment by shellscape** [comment]
@lutangar if this ends up still being an issue for you after the latest version, please reply and we'll reopen the issue to triage further.

**Comment by lutangar** [comment]
Alright, I'll keep you posted. Thanks.

**Comment by jonesnc** [comment]
I was having this problem as well.

Installing the `webpack-hot-client` package from my own project seems to have fixed it.

**Comment by frenzzy** [comment]
Solution is here: https://github.com/webpack-contrib/webpack-hot-client/pull/62
